# Generated by Django 4.1.10 on 2023-08-17 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Profile_Picture', models.ImageField(upload_to='')),
                ('Username', models.CharField(max_length=200)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Line1', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=1000)),
                ('pincode', models.IntegerField(max_length=100)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.users')),
            ],
        ),
    ]
