# Generated by Django 4.1.10 on 2023-08-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Line1',
            new_name='Line',
        ),
    ]
