# Generated by Django 4.1.10 on 2023-08-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_line1_address_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
